# Use postgres/example user/password credentials

services:
  db:
    image: postgres:17-alpine
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
